{{- if (index .Values "image-registry-credentials") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: image-registry-credentials
  namespace: {{ .Release.Name }}-challenges
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ (index  .Values "image-registry-credentials") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: image-registry-credentials
  namespace: {{ .Release.Name }}-challenges-isolated
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ (index  .Values "image-registry-credentials") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: image-registry-credentials
  namespace: {{ .Release.Name }}-management
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ (index  .Values "image-registry-credentials") }}
{{- end }}
